-- Supabase Database Schema for Jobbeagle
-- Run this SQL in your Supabase SQL Editor

-- Table: analysis_reports
-- Stores the analysis reports generated by Gemini
CREATE TABLE IF NOT EXISTS analysis_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  job_title TEXT,
  job_description TEXT NOT NULL,
  resume_file_name TEXT,
  resume_type TEXT CHECK (resume_type IN ('text', 'file')),
  analysis_data JSONB NOT NULL,
  content TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: resume_history
-- Stores uploaded resume files for quick access
CREATE TABLE IF NOT EXISTS resume_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('text', 'file')),
  content TEXT NOT NULL,
  mime_type TEXT,
  file_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_analysis_reports_created_at ON analysis_reports(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analysis_reports_user_id ON analysis_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_resume_history_created_at ON resume_history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_resume_history_user_id ON resume_history(user_id);

-- Enable Row Level Security (RLS)
ALTER TABLE analysis_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE resume_history ENABLE ROW LEVEL SECURITY;

-- Create policies (adjust based on your authentication needs)
-- For now, allow all operations (you may want to restrict based on user authentication)
CREATE POLICY "Allow all operations on analysis_reports" ON analysis_reports
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow all operations on resume_history" ON resume_history
  FOR ALL USING (true) WITH CHECK (true);

-- RLS Policies for user-specific data access
-- Users can only see their own reports
CREATE POLICY "Users can only see their own reports" ON analysis_reports
  FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL);
  
-- Users can only insert their own reports
CREATE POLICY "Users can only insert their own reports" ON analysis_reports
  FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

-- Users can only see their own resume history
CREATE POLICY "Users can only see their own resume history" ON resume_history
  FOR SELECT USING (auth.uid() = user_id);
  
-- Users can only insert their own resume history
CREATE POLICY "Users can only insert their own resume history" ON resume_history
  FOR INSERT WITH CHECK (auth.uid() = user_id);
  
-- Users can only delete their own resume history
CREATE POLICY "Users can only delete their own resume history" ON resume_history
  FOR DELETE USING (auth.uid() = user_id);
