-- Supabase Database Schema for Jobbeagle
-- Run this SQL in your Supabase SQL Editor

-- Table: analysis_reports
-- Stores the analysis reports generated by Gemini
CREATE TABLE IF NOT EXISTS analysis_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_description TEXT NOT NULL,
  resume_file_name TEXT,
  resume_type TEXT CHECK (resume_type IN ('text', 'file')),
  report_data JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: resume_history
-- Stores uploaded resume files for quick access
CREATE TABLE IF NOT EXISTS resume_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL CHECK (type IN ('text', 'file')),
  content TEXT NOT NULL,
  mime_type TEXT,
  file_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_analysis_reports_created_at ON analysis_reports(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_resume_history_created_at ON resume_history(created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE analysis_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE resume_history ENABLE ROW LEVEL SECURITY;

-- Create policies (adjust based on your authentication needs)
-- For now, allow all operations (you may want to restrict based on user authentication)
CREATE POLICY "Allow all operations on analysis_reports" ON analysis_reports
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow all operations on resume_history" ON resume_history
  FOR ALL USING (true) WITH CHECK (true);

-- Optional: If you want to add user authentication later, uncomment and modify:
-- CREATE POLICY "Users can only see their own reports" ON analysis_reports
--   FOR SELECT USING (auth.uid() = user_id);
-- 
-- CREATE POLICY "Users can only insert their own reports" ON analysis_reports
--   FOR INSERT WITH CHECK (auth.uid() = user_id);
